---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[znc::default]
    attributes:
      znc:
        user: "test_user"
        pass: "test_pass"
        salt: "12345678901234567890"
        port: 5432
