---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[znc::default]
    attributes:
      znc:
        users:
          - nick: "test_user_1"
            pass: "test_pass_1"
            salt: "12345678901234567890"
          - nick: "test_user_2"
            pass: "test_pass_2"
            salt: "09876543210987654321"
        port: 5432
